In [14]:
import pandas as pd

df = pd.read_csv('AI_Impact_Student_Life_2026.csv')
df['Diference_GPA'] = df['GPA_Baseline'] - df['GPA_Post_AI']
df_notas = df.drop(columns=['Student_ID'])
display(df_notas)
display(df_notas.info())

,Age,Major,Primary_AI_Tool,Task_Frequency_Daily,Main_Usage_Case,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,AI_Ethics_Concern,Career_Confidence_Score,Diference_GPA
0,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3,0.00
1,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4,-0.01
2,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7,0.00
3,19,Biology,Claude 3.5,5,Essay Drafting,2.67,2.87,12,Low,5,-0.20
4,19,Biology,ChatGPT-4o,10,Code Debugging,3.65,3.85,5,High,9,-0.20
...,...,...,...,...,...,...,...,...,...,...,...
1495,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7,-0.20
1496,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7,-0.30
1497,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2,-0.20
1498,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7,-0.01
1499,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8,0.10

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1500 non-null   int64
 1   Major                    1500 non-null   object
 2   Primary_AI_Tool          1500 non-null   object
 3   Task_Frequency_Daily     1500 non-null   int64
 4   Main_Usage_Case          1500 non-null   object
 5   GPA_Baseline             1500 non-null   float64
 6   GPA_Post_AI              1500 non-null   float64
 7   Time_Saved_Hours_Weekly  1500 non-null   int64
 8   AI_Ethics_Concern        1500 non-null   object
 9   Career_Confidence_Score  1500 non-null   int64
 10  Diference_GPA            1500 non-null   float64
dtypes: float64(3), int64(4), object(4)
memory usage: 129.0+ KB

None

In [16]:
# Criação de dataframe para relacionar confiança na carreira, GPA, frequência de uso, idade e curso

df_confidence = df_notas[['Age','Major','Task_Frequency_Daily','GPA_Baseline','Career_Confidence_Score']]
df_confidence.to_csv('df_confidence.csv')
display(df_confidence)

,Age,Major,Task_Frequency_Daily,GPA_Baseline,Career_Confidence_Score
0,23,Software Engineering,1,2.62,3
1,22,Modern History,3,3.99,4
2,18,Data Science,2,2.57,7
3,19,Biology,5,2.67,5
4,19,Biology,10,3.65,9
...,...,...,...,...,...
1495,21,Modern History,4,3.35,7
1496,21,Biology,3,3.59,7
1497,23,Software Engineering,8,3.20,2
1498,23,Fine Arts,6,3.99,7
1499,23,Data Science,4,3.53,8