In [3]:
import pandas as pd

df = pd.read_csv('AI_Impact_Student_Life_2026.csv')
df['Difference_GPA'] = df['GPA_Baseline'] - df['GPA_Post_AI']
df_notas = df.drop(columns=['Student_ID'])
display(df_notas)
display(df_notas.info())

,Age,Major,Primary_AI_Tool,Task_Frequency_Daily,Main_Usage_Case,GPA_Baseline,GPA_Post_AI,Time_Saved_Hours_Weekly,AI_Ethics_Concern,Career_Confidence_Score,Difference_GPA
0,23,Software Engineering,Gemini Pro,1,Code Debugging,2.62,2.62,9,Medium,3,0.00
1,22,Modern History,GitHub Copilot,3,Essay Drafting,3.99,4.00,7,Medium,4,-0.01
2,18,Data Science,Perplexity,2,Literature Review,2.57,2.57,15,High,7,0.00
3,19,Biology,Claude 3.5,5,Essay Drafting,2.67,2.87,12,Low,5,-0.20
4,19,Biology,ChatGPT-4o,10,Code Debugging,3.65,3.85,5,High,9,-0.20
...,...,...,...,...,...,...,...,...,...,...,...
1495,21,Modern History,GitHub Copilot,4,Brainstorming,3.35,3.55,7,Medium,7,-0.20
1496,21,Biology,GitHub Copilot,3,Essay Drafting,3.59,3.89,13,Medium,7,-0.30
1497,23,Software Engineering,GitHub Copilot,8,Code Debugging,3.20,3.40,7,Low,2,-0.20
1498,23,Fine Arts,Perplexity,6,Brainstorming,3.99,4.00,15,Low,7,-0.01
1499,23,Data Science,Gemini Pro,4,Exam Prep,3.53,3.43,3,Medium,8,0.10

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1500 entries, 0 to 1499
Data columns (total 11 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      1500 non-null   int64
 1   Major                    1500 non-null   object
 2   Primary_AI_Tool          1500 non-null   object
 3   Task_Frequency_Daily     1500 non-null   int64
 4   Main_Usage_Case          1500 non-null   object
 5   GPA_Baseline             1500 non-null   float64
 6   GPA_Post_AI              1500 non-null   float64
 7   Time_Saved_Hours_Weekly  1500 non-null   int64
 8   AI_Ethics_Concern        1500 non-null   object
 9   Career_Confidence_Score  1500 non-null   int64
 10  Difference_GPA           1500 non-null   float64
dtypes: float64(3), int64(4), object(4)
memory usage: 129.0+ KB

None

In [ ]:
# Filtragem de dados para relacionar confiança na carreira, GPA, frequência de uso e idade

df_confidence = df_notas[['Age','Major','Task_Frequency_Daily','GPA_Baseline','Career_Confidence_Score']]
df_confidence.to_csv('df_confidence.csv')
display(df_confidence)

,Age,Major,Task_Frequency_Daily,GPA_Baseline,Career_Confidence_Score
0,23,Software Engineering,1,2.62,3
1,22,Modern History,3,3.99,4
2,18,Data Science,2,2.57,7
3,19,Biology,5,2.67,5
4,19,Biology,10,3.65,9
...,...,...,...,...,...
1495,21,Modern History,4,3.35,7
1496,21,Biology,3,3.59,7
1497,23,Software Engineering,8,3.20,2
1498,23,Fine Arts,6,3.99,7
1499,23,Data Science,4,3.53,8

In [ ]:
# Filtragem de dados para análise de relação entre curso, frequência de uso e tempo salvo

df_efficiency = df_notas[['Age','Major','Task_Frequency_Daily','Time_Saved_Hours_Weekly','Difference_GPA']]
df_cursos = df_efficiency[['Major','Time_Saved_Hours_Weekly','Task_Frequency_Daily']].groupby(['Major','Task_Frequency_Daily']).mean()
df_cursos.to_csv('df_cursos.csv')
display(df_efficiency)
display(df_cursos)
display(df_cursos.describe())

,Age,Major,Task_Frequency_Daily,Time_Saved_Hours_Weekly,Difference_GPA
0,23,Software Engineering,1,9,0.00
1,22,Modern History,3,7,-0.01
2,18,Data Science,2,15,0.00
3,19,Biology,5,12,-0.20
4,19,Biology,10,5,-0.20
...,...,...,...,...,...
1495,21,Modern History,4,7,-0.20
1496,21,Biology,3,13,-0.30
1497,23,Software Engineering,8,7,-0.20
1498,23,Fine Arts,6,15,-0.01
1499,23,Data Science,4,3,0.10

                                              Time_Saved_Hours_Weekly
Major                   Task_Frequency_Daily
Biology                 1                                    9.371429
                        2                                    8.555556
                        3                                    8.555556
                        4                                    8.518519
                        5                                    8.370370
                        6                                    8.650000
                        7                                    7.458333
                        8                                    7.600000
                        9                                    8.833333
                        10                                   8.217391
Business Administration 1                                    7.851852
                        2                                   10.000000
                        3                                   10.450000
                        4                                    7.080000
                        5                                    8.392857
                        6                                    8.793103
                        7                                    8.481481
                        8                                    9.032258
                        9                                    8.958333
                        10                                   9.000000
Data Science            1                                    7.535714
                        2                                   10.137931
                        3                                    8.272727
                        4                                    8.076923
                        5                                    9.200000
                        6                                    8.857143
                        7                                    9.363636
                        8                                    9.323529
                        9                                    8.333333
                        10                                   8.480000
Fine Arts               1                                    7.833333
                        2                                    9.137931
                        3                                    7.551724
                        4                                    9.285714
                        5                                    8.370370
                        6                                    8.451613
                        7                                    8.333333
                        8                                    8.000000
                        9                                    8.238095
                        10                                   6.454545
Modern History          1                                    7.157895
                        2                                    9.440000
                        3                                    8.730769
                        4                                    9.000000
                        5                                    7.846154
                        6                                    7.500000
                        7                                   10.214286
                        8                                    9.318182
                        9                                    8.555556
                        10                                   7.500000
Software Engineering    1                                    8.000000
                        2                                    8.771429
                        3                                    8.526316
                        4                                    8.000000
                        5                                    7.181818
                        6                                    8.000000
                        7                                    8.200000
                        8                                    9.344828
                        9                                    7.903226
                        10                                   9.884615

       Time_Saved_Hours_Weekly
count                60.000000
mean                  8.508051
std                   0.820437
min                   6.454545
25%                   8.000000
50%                   8.480741
75%                   9.008065
max                  10.450000

In [25]:
# Filtragem de dados para relacionar para quais tarefas e quais ferramentas de IA mais são utilizadas por cada curso

df_uso = df_notas[['Major','Primary_AI_Tool','Main_Usage_Case']].groupby(['Major','Primary_AI_Tool','Main_Usage_Case']).size().reset_index()
display(df_uso)
df_uso.to_csv('df_uso.csv')

                    Major Primary_AI_Tool    Main_Usage_Case   0
0                 Biology      ChatGPT-4o      Brainstorming   7
1                 Biology      ChatGPT-4o     Code Debugging   7
2                 Biology      ChatGPT-4o     Essay Drafting  11
3                 Biology      ChatGPT-4o          Exam Prep  16
4                 Biology      ChatGPT-4o  Literature Review  13
..                    ...             ...                ...  ..
145  Software Engineering      Perplexity      Brainstorming   9
146  Software Engineering      Perplexity     Code Debugging  10
147  Software Engineering      Perplexity     Essay Drafting   6
148  Software Engineering      Perplexity          Exam Prep  12
149  Software Engineering      Perplexity  Literature Review  14

[150 rows x 4 columns]